version: "3.3"

services:

  nginx:
    # Reload nginx every 12 hours to poll for new certificate
    # refreshes which happen in the background.
    command: /bin/bash -c "\
      while :; do \
        sleep 12h & wait $${!}; \
        nginx -s reload; \
      done & \
      nginx -g \"daemon off;\" \
      "
    volumes:
      - https-certs-vol:/etc/letsencrypt
      - www-certbot-vol:/var/www/certbot

