name: Run Type Checks
on: [push, pull_request, workflow_dispatch]

jobs:
  type-checks:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install Dependencies
      run: |
        pip install mypy
        pip install typer
    - name: mypy
      run: |
        mypy init-odkx-sync-endpoint.py